[build]
  base = "/opt/build/repo"

  # next exportの出力先
  publish = "/opt/build/repo/out"

  # next buildからのnext exportでファイル生成
  command = "NODE_ENV=production yarn run build && yarn run export"
  commandOrigin = "config"

[context.production]
  command = "NODE_ENV=production yarn run build && yarn run export"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200